name: antarctic_plots
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  # Science
  - numpy
  - pandas
  - geopandas
  - pooch
  - pygmt
  - pyproj
  - rioxarray
  - verde
  - xarray
  # Build
  - setuptools
  - twine
  # Code style checks and autoformat
  - black
  - isort
  - flake8
  # iPython
  - ipykernel
  - notebook
  - jupyterlab
