[tool.poetry]
name = "antarctic_plots"
version = "0.1.0"
description = "Functions to automate Antarctic data visualization"
authors = ["Matt Tankersley <matt.d.tankersley@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
