[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "antarctic_plots"
authors = [{name = "Matt Tankersley", email = "matt.d.tankersley@gmail.com"}]
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "pandas",
    "numpy",
    "pooch",
    "xarray",
    "pyproj",
    "verde",
    "rioxarray",
    "netCDF4",
]

[project.optional-dependencies]
dev = [
    "black[jupyter]",
    "flake8",
    "isort",
    "pytest",
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
    "furo",
    "nbsphinx",
    "sphinx-autoapi",
]
ipython = [
    "ipykernel",
    "jupyterlab",
    "notebook",
]

[project.urls]
Source = "https://github.com/mdtanker/antarctic_plots"
