# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-22.04]

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install package dependencies
      - name: Install dependencies
        run: pip install --no-deps --requirement requirements.txt
      # Run tests and create coverage report, try replacing with pytest --cov=antarctic_plots antarctic_plots/tests/
      - name: Test with pytest
        run: pytest --cov=antarctic_plots antarctic_plots/tests/
      # Upload coverage report to codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3